Sunoo/homebridge-camera-ffmpeg

README.md
ffmpeg.js

* Report error when ffmpeg fails
* Use SIGTERM to quit ffmpeg

Add callback for ffmpeg process exit

---

README.md
ffmpeg.js

Hi
I added two new configuration keys that allow a more fine-grained control of the video output.  Please pull if appropriate.
Ciao
Francesco

New config keys 'minBitrate' and 'preserveRatio'

---

config.schema.json

- Add vflip, hflip, motion and upload keys

Add vflip, hflip, motion and upload keys to config schema

---

config.schema.json
package.json

Hi @KhaosT 
These config.schema.json changes make it a bit easier to use via Homebridge Config UI X, and include some extra properties that have been added in the last while.
Also bumped ffmpeg-for-homebridge to 0.0.4 - this doesn't change any functionality, it just makes the error messages look less intimidating.

Update config.schema and ffmpeg-for-homebridge dep

---

.github/workflows/nodejs.yml
CHANGELOG.md
README.md
config.schema.json
index.js
package-lock.json
package.json

This PR optionally makes a camera-ffmpeg camera behave like a video doorbell and adds a switch that can be used to trigger a video doorbell event (notification).

add video doorbell functionality

---

.github/workflows/nodejs-beta.yml
.github/workflows/prerelease.js
CHANGELOG.md
README.md
ffmpeg.js
package-lock.json
package.json

* Adds debug log for `videoProcessor`.

Version 1.1.1

---

index.js

As the title says, currently the motion switch doesn't reset when the doorbell function is enabled at the same time. Fixes, cleans up and condenses the code around the motion switch.

motion switch cleanups - Fixes #522

---

CHANGELOG.md
index.js
package-lock.json
package.json

During testing found that the Fake Motion Sensor is not reset after the Motion Trigger switch is reset in 5 seconds.

Fake Motion Sensor is not reset after Motion Event

---

package-lock.json
package.json

Bump the version of ffmpeg-for-homebridge to fix the issue with ALSA.

Update ffmpeg-for-homebridge to 0.0.6

---

src/index.ts

This should fix #579 as it now always uses the latest configuration specified in the config.json.
I don't have this plugin set up, so testing this PR first might be advised.

Ensure that configureAccessory always uses the latest configuration provided by the config file

---

src/index.ts

This PR updates the MQTT client to only try to establish a connection of the `mqtt` (aka the hostname of the MQTT broker) config property is defined.

Only create an mqtt client if a mqtt host is configured

---

src/index.ts

#575 fix for services with same UUID

fix home bridge restart issues (service with same UUID no removed)

---

src/ffmpeg.ts
src/streamingDelegate.ts

This fixes #595 where some logs were not showing up.

Logging updates

---

src/index.ts

The current versions dump a copy of the camera config in the accessory context during the initial configuration, then never use it again, except for when the camera is deleted. I removed all that, since there is no need for it to be there.
I also made minor tweaks to some of the logging. I think we should also consider moving most of the logging to debug level, as it adds a lot of noise, but I didn't do that here.

Stop Storing Stale Config in Context

---

src/index.ts

This will allow you to change the manufacturer, model, serial number, and firmware revision after the first restart after adding the camera. This should fix issues like #632 .
I also renamed a few variables to be more consistent and less confusing.

Fix for Changing Manufacturer, Model, etc.

---

CHANGELOG.md
package-lock.json
package.json
src/index.ts

Fixed bug preventing Homebridge from starting. (#640)

Version 2.2.1

---

CHANGELOG.md
config.schema.json
package.json
src/ffmpeg.ts
src/index.ts
src/streamingDelegate.ts

* Restored ability to specify which network interface to use.
* Fixed handling of non-printing characters in config.

Version 2.2.2

---

config.schema.json
package-lock.json
package.json
src/index.ts
src/streamingDelegate.ts
tsconfig.json

* Added HTTP support for motion detection and doorbells.
* Separated MQTT doorbell and motion messages.

Version 2.3.0

---

package-lock.json
package.json
src/ffmpeg.ts
src/index.ts
src/streamingDelegate.ts

- Update dependencies.
- FFmpeg processes are now killed when the iOS device goes inactive and when stopping Homebridge.

Version 2.3.2

---

CHANGELOG.md
package.json
src/index.ts
src/streamingDelegate.ts

- Added warning when multiple NICs detected.
- Fix error using copy vcodec.

Version 2.4.1

---

.github/workflows/publish-beta.yml
CHANGELOG.md
README.md
config.schema.json
package-lock.json
package.json
src/configTypes.ts
src/index.ts

- Trigger switches are now turned on and off with HTTP or MQTT messages as well.
- Removed doorbell stateless switch because it had no functionality.

Version 2.4.3

---

CHANGELOG.md
README.md
config.schema.json
package-lock.json
package.json
src/configTypes.ts
src/ffmpeg.ts
src/index.ts
src/streamingDelegate.ts

- Added support for unbridging specific cameras.This can aid with performance of the camera and Homebridge as a whole, but requires manually adding any unbridged cameras to HomeKit.

Version 2.4.4

---

CHANGELOG.md
config.schema.json
package-lock.json
package.json
src/index.ts

- Return messages and error codes when using HTTP automation.
- Fixed bug preventing MQTT/HTTP automation from working.

Version 2.4.5

---

CHANGELOG.md
package.json
src/index.ts

- Fix MQTT/HTTP automation when unbridge is used.

Version 2.4.6

---

CHANGELOG.md
package-lock.json
package.json
src/index.ts
src/streamingDelegate.ts

- Changed the way external IP address is determined. This should result in video streams working by default in more setups.

Version 2.4.7

---

CHANGELOG.md
package-lock.json
package.json
src/streamingDelegate.ts

- Fixed an issue with inactive camera timeouts that could cause zombie FFmpeg processes.

Version 3.0.1
