Sunoo/homebridge-camera-ffmpeg

README.md, ffmpeg.js
Allows for very fast snapshot grabs on certain cameras (e.g. my Foscams) which speeds up UI timeliness a lot.
=> Add `stillImageSource` option in config.json

ffmpeg.js
Looks like all the comparison operators for video resolution selection are backwards. Lower resolutions should be selected when `maxWidth`/`maxHeight` are *greater than* or equal to the resolution to include.
This bug was causing resolutions higher than `maxWidth`/`maxHeight` to be selected so if you chose for example 1280x720 as max resolution, it would also include 1920x1080 and none of the lower resolutions. For me at least, that mean't the live stream wouldn't work on Apple Watch or iPhone on LTE.
=> Fix video resolution selection

README.md, drive.js, ffmpeg.js, index.js, package.json, quickstart.js
I'm using this in combination with a motion sensor to watch my front porch, and see who is coming and going, but what I felt was lacking was storage of the pictures.  They would appear on my phone, allowing a quick view but would go away afterwards not allowing you to store a picture for later.
This pull request adds the functionality without forcing usage, and if it isn't configured the plugin continues to work normally.
I also added as a config parameter vcodec, so that you could use alternate video codecs like the RaspberryPI optimized h264_omx without resorting to editing ffmpeg.js.
=> Support for storing snapshots into your google drive account.

README.md, ffmpeg.js, index.js
- add support for audio streams
- add support for changing packet size via config file
- apply MaxFPS to video output
- small cleanups
I combined the various info on audio and added (optional) support for audio to the plugin.
The MaxFPS was only used to supply video formats but as HomeKit seems to ask for a higher framerate anyway I use it to cap the video output now.
I also organized the ffmpeg command creation a bit so that it's easier to make (and see) changes. I removed the "-tune" parameter as it doesn't seem to work in the latest version of ffmpeg.
I thought a PR was in order, just close it if theres no interest, if changes are required tell me.
=> Add audio support

README.md, ffmpeg.js, index.js
This PR creates default values for most parameters so they don't have to be entered in the config file for each camera. Notably it limits the frame rate to 10 fps by default as this seems to greatly improve the latency and video quality on the iOS side for my various cameras. Otherwise the values are basically left as they were. It also updates the README.
I'd be happy if the PR would not be squashed but simply merged so I can continue working in my forked repo without having messy future PRs or having to delete it each time I want to make a PR for this project :)
=> Add default values for most parameters

ffmpeg.js, package.json
- This will allow passing additional command line options via config to ffmpeg. If none are set, it will pass **-tune zerolatency**.
- Also always setup a stderr listener on ffmpeg process to avoid steam from stopping every minute or two.
=> Allow passing additional command line options to ffmpeg.

README.md, ffmpeg.js
Hello, this PR has *not* been tested thoroughly. It is in response to #258 #261 so that hardcoded arguments can be more easily overridden for testing.
The main focus of the changes are to intervene before the external process is spawned, so the arguments can be output with the overriding value (if set). Additionally, the README has been updated with information about this new parameter as well as the missing `additionalCommandLine` option.
=> Enable custom arguments to be passed to video processor

README.md
This may make audio functional when ffmpeg does not include libfdk-aac.
=> Add documentation on how to force OPUS codec

README.md, ffmpeg.js, index.js
Useful for hosts with multiple network interfaces. See issue #317
=> Add ‘interfaceName’ optional configuration

README.md, drive.js, index.js, package.json
Workaround for iOS 13, and the requirement for motion sensors to be part of a camera in order for picture notifications.  Creates a dummy motion sensor and switch as part of the camera, and the switch turns the motion sensor on.  The motion sensor is automatically turned off after 5 seconds.
To enable picture notifications, create an Automation in the home app that turns on the dummy switch when the real motion sensor detects motion.
Also includes pull request #309
=> Workaround for #332 - iOS 13 Picture Notifications

ffmpeg.js, package.json
* [ffmpeg for homebridge](https://github.com/homebridge/ffmpeg-for-homebridge)
@KhaosT any chance we can get this implemented to make it easier for users when using this plugin?
=> Add ffmpeg-for-homebridge dependency

index.js
Hey @KhaosT,  Since Homebridge v1.0.0, users have bee seeing this log.
`One of your plugins incorrectly registered an external accessory using the platform name (Camera-ffmpeg) and not the plugin identifier. Please report this to the developer!`
This is a fix for this log, so that it is registering to the correct platform name.
- This fixes homebridge issue [#2547](https://github.com/homebridge/homebridge/issues/2547).
- also fixes #465.
Thanks!
=> Fix #465: incorrectly registered an external accessory

ffmpeg.js
Fix for issue #438.
vflip and hflip filters will now act on stillImageSource snapshots and will be set when videoFilter is null as well as an empty string.
=> Fix #438 vflip not working

ffmpeg.js
Do not set video filters if the copy video codec is used as raised in issue #474.
=> Fix #474 - copy vcodec and filters

CHANGELOG.md, README.md, index.js, package.json
When debugging why I could not use the proper audio codec provided by ffmpeg-for-homebridge found that it was using the OS installed version.
=> ffmpeg-for-homebridge is not being utilized

package-lock.json, package.json
This update adds support for the [`speex`](https://www.speex.org/) codec and support for using [`alsa`](https://www.alsa-project.org/wiki/Main_Page) drivers for audio input.
=> Bump ffmpeg-for-homebridge

config.schema.json, package.json, src/index.ts
Just publish to topic, no message, homebridge/motion/Camera_name.
You must add _ to your camera if you have space in the name.
```
{
"platform": "Camera-ffmpeg",
"mqtt": "127.0.0.1",
"topics": "homebridge/motion/#",
"portmqtt": 1883,
"cameras": [
{
"name": "Camera name",
"motion": true,
"videoConfig": {
"source": "-re -i http://10.0.0.1",
"stillImageSource": "-i http://10.0.0.1",
"maxStreams": 5,
"maxWidth": 1280,
"maxHeight": 720,
"maxFPS": 15,
"maxBitrate": 1000
}
}
]
}
```
=> Add MQTT to motion Detect 

src/streamingDelegate.ts
- Fix using the config `packetSize` when configuring ffmpeg `pkt_size`, if not set, fallback to `video.mtu` (fixes #564)
- Fixed declaring `this.debug` twice
- Refactor most ffmpeg code to always use class properties rather than `ffmpegOpt` directly (makes defaults more consistent and less duplicated)
- Fix "Starting video stream" to log without debug mode enabled (like it did in v1.3.0)
=> Fix packetsize config and various refactoring

src/streamingDelegate.ts
The HAP-NodeJS camera example uses `-vframes 1` to capture just one frame https://github.com/homebridge/HAP-NodeJS/blob/master/src/accessories/Camera_accessory.ts#L71
`-frames:v` is the newer version of `-vframes` which is deprecated https://ffmpeg.org/ffmpeg.html#Video-Options
=> Tweak image snapshot to use -frames:v instead of -t

config.schema.json, src/index.ts
As discussed in #575 this adds support for resetting the motion sensor via MQTT.
To reset the sensor, publish a message with the camera name to `topic`/reset . So the default would be 'homebridge/motion/reset'.
If you're using MQTT to reset the sensor, you probably don't want the timeout firing to automatically reset the sensor, so I added a configuration option for the number of seconds for the timeout to fire. It defaults to 1, like the previous code worked. However, if you set it to -1, that timeout will be disabled, so the sensor will stay active until the reset MQTT message is received.
=> Support for MQTT Resetting of Motion Sensor

src/index.ts
I found the problem with the caching of the timeout in the MQTT motion stuff I worked on, and corrected it here.
While I was in the code, it seemed to make sense for the other timeouts related to the switches for motion and doorbell to follow that same timeout value. They weren't even consistent with each other before.
=> Better Handling of Timeout Config Option

config.schema.json, src/index.ts
This should resolve the bug identified in #621 , if the doorbellSwitch config option is set, the plugin will fail after the first time you restart Homebridge.
=> Fix bug with doorbell switch

.eslintrc.js, CHANGELOG.md, README.md, config.schema.json, package-lock.json, package.json, src/configTypes.ts, src/ffmpeg.ts, src/streamingDelegate.ts, tsconfig.json
- `forceMax` has been added. This will force the use of `maxWidth`, `maxHeight`, `maxFPS`, and `maxBitrate` when set.
- If `maxWidth`, `maxHeight`, or `maxFPS` are set to `0`, the width, height, or framerate of the source will now be used for the output.
- If `maxBitrate` is set to `0`, the bitrate of the encoder will not be limited. I strongly recommend against this, but it is a better option than setting it to `999999` or similar values, as I've seen in some configs.
- Reorganized config UI options.
- Fix handling of IPv6 connections.
- Horizontal and vertical flip have been removed. If you need these options, pass `hflip` and/or `vflip` in `videoFilter`.
- `forceMax` has resulted in the removal of `minBitrate`, as it is now redundant. To replicate the old behavior, set `maxBitrate` to …
=> Version 2.5.0

CHANGELOG.md, README.md, config.schema.json, package-lock.json, package.json, src/configTypes.ts, src/ffmpeg.ts, src/streamingDelegate.ts
- This plugin now includes __experimental__ two-way audio support. Be aware that this feature is likely to be tweaked in the future, and a configuration that works now may need to be altered in the future.
- Better detection of audio and video streams. There should be very few scenarios where `mapvideo` or `mapaudio` are needed anymore, as FFmpeg's stream auto-selection is now set up.
- Default `videoFilter` can be disabled by including `none` in your comma-delimited list of filters.
- Further reorganization of the config UI.
- Corrected handling of inactive camera timeouts. You should no longer see timeout messages after cleanly closing a camera stream.
- Fixed `forceMax` not applying to resolution in some scenarios.
- `additionalCommandline` has been replaced by `encoderOptions` to …
=> Version 3.0.0

src/streamingDelegate.ts
`err.name` would just return `Error` whereas `err.message`  would return `bind EACCES 0.0.0.0:57431`
RE: https://github.com/Sunoo/homebridge-camera-ffmpeg/issues/1087
=> Show error message on socket error

src/ffmpeg.ts
Fixed reconnection problem for rtsp stream. Stream was killed and not gracefully shut down. This was a problem for at least Reolink cameras. With the fix, my Reolink camera is working reliable with this plugin.
see https://github.com/Sunoo/homebridge-camera-ffmpeg/issues/1134
=> Added graceful termination of rtsp stream
